config:
  aws:region: us-west-2
  origin:env: prod
  origin:vpcCidr: 10.50.0.0/16
  origin:publicSubnetCidr: 10.50.1.0/24
  origin:privateSubnetCidr: 10.50.10.0/24
  origin:instanceType: m7gd.medium
  origin:rootDomain: example.com
  origin:subdomain: api
  origin:cloudflareAccountId: CHANGE_ME_ACCOUNT_ID
  origin:cloudflareZoneId: CHANGE_ME_ZONE_ID
  origin:tunnelName: origin-prod
  origin:servicePort: "8080"
  origin:ssmPathPrefix: /origin
  origin:wasmcloudVersion: 1.2.1
  origin:surrealdbVersion: 2.2.1
  origin:tunnelSecret: CHANGE_ME_BASE64_32_BYTE_SECRET
  origin:surrealdbRootPassword: CHANGE_ME_PROD_DB_PASSWORD
